
package com.example.HotelTP.agency.clients.h1;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelService", targetNamespace = "http://service.server.HotelSOAP.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelService {


    /**
     * 
     * @param password
     * @param agencyId
     * @return
     *     returns java.util.List<com.example.HotelTP.agency.clients.h1.Reservation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReservationsForAgencys", targetNamespace = "http://service.server.HotelSOAP.example.com/", className = "com.example.HotelTP.agency.clients.h1.GetReservationsForAgencys")
    @ResponseWrapper(localName = "getReservationsForAgencysResponse", targetNamespace = "http://service.server.HotelSOAP.example.com/", className = "com.example.HotelTP.agency.clients.h1.GetReservationsForAgencysResponse")
    @Action(input = "http://service.server.HotelSOAP.example.com/HotelService/getReservationsForAgencysRequest", output = "http://service.server.HotelSOAP.example.com/HotelService/getReservationsForAgencysResponse")
    public List<Reservation> getReservationsForAgencys(
        @WebParam(name = "agencyId", targetNamespace = "")
        String agencyId,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param password
     * @param offerId
     * @param client
     * @param agencyId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "book", targetNamespace = "http://service.server.HotelSOAP.example.com/", className = "com.example.HotelTP.agency.clients.h1.Book")
    @ResponseWrapper(localName = "bookResponse", targetNamespace = "http://service.server.HotelSOAP.example.com/", className = "com.example.HotelTP.agency.clients.h1.BookResponse")
    @Action(input = "http://service.server.HotelSOAP.example.com/HotelService/bookRequest", output = "http://service.server.HotelSOAP.example.com/HotelService/bookResponse")
    public String book(
        @WebParam(name = "agencyId", targetNamespace = "")
        String agencyId,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "offerId", targetNamespace = "")
        String offerId,
        @WebParam(name = "client", targetNamespace = "")
        Client client);

    /**
     * 
     * @param persons
     * @param password
     * @param endDate
     * @param agencyId
     * @param startDate
     * @return
     *     returns java.util.List<com.example.HotelTP.agency.clients.h1.AvailabilityOffer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkAvailability", targetNamespace = "http://service.server.HotelSOAP.example.com/", className = "com.example.HotelTP.agency.clients.h1.CheckAvailability")
    @ResponseWrapper(localName = "checkAvailabilityResponse", targetNamespace = "http://service.server.HotelSOAP.example.com/", className = "com.example.HotelTP.agency.clients.h1.CheckAvailabilityResponse")
    @Action(input = "http://service.server.HotelSOAP.example.com/HotelService/checkAvailabilityRequest", output = "http://service.server.HotelSOAP.example.com/HotelService/checkAvailabilityResponse")
    public List<AvailabilityOffer> checkAvailability(
        @WebParam(name = "agencyId", targetNamespace = "")
        String agencyId,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "startDate", targetNamespace = "")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        String endDate,
        @WebParam(name = "persons", targetNamespace = "")
        int persons);

}
