
package com.example.HotelTP.agency.clients.h1;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelService", targetNamespace = "http://hotel.example.com/soap")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelService {


    /**
     * 
     * @param password
     * @param mainGuest
     * @param offerId
     * @param agencyId
     * @param login
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "book", targetNamespace = "http://hotel.example.com/soap", className = "com.example.HotelTP.agency.clients.h1.Book")
    @ResponseWrapper(localName = "bookResponse", targetNamespace = "http://hotel.example.com/soap", className = "com.example.HotelTP.agency.clients.h1.BookResponse")
    @Action(input = "http://hotel.example.com/soap/HotelService/bookRequest", output = "http://hotel.example.com/soap/HotelService/bookResponse")
    public String book(
        @WebParam(name = "agencyId", targetNamespace = "")
        String agencyId,
        @WebParam(name = "login", targetNamespace = "")
        String login,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "offerId", targetNamespace = "")
        String offerId,
        @WebParam(name = "mainGuest", targetNamespace = "")
        Client mainGuest);

    /**
     * 
     * @param persons
     * @param password
     * @param start
     * @param agencyId
     * @param end
     * @return
     *     returns java.util.List<com.example.HotelTP.agency.clients.h1.AvailabilityOffer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkAvailability", targetNamespace = "http://hotel.example.com/soap", className = "com.example.HotelTP.agency.clients.h1.CheckAvailability")
    @ResponseWrapper(localName = "checkAvailabilityResponse", targetNamespace = "http://hotel.example.com/soap", className = "com.example.HotelTP.agency.clients.h1.CheckAvailabilityResponse")
    @Action(input = "http://hotel.example.com/soap/HotelService/checkAvailabilityRequest", output = "http://hotel.example.com/soap/HotelService/checkAvailabilityResponse")
    public List<AvailabilityOffer> checkAvailability(
        @WebParam(name = "agencyId", targetNamespace = "")
        String agencyId,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "start", targetNamespace = "")
        String start,
        @WebParam(name = "end", targetNamespace = "")
        String end,
        @WebParam(name = "persons", targetNamespace = "")
        int persons);

}
