package com.example.HotelSOAP.comparator.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.ArrayList;
import java.util.List;

@Controller
public class ComparatorController {

  // Inject SOAP clients generated by wsimport
  @Autowired
  @Qualifier("a1Client")
  private com.example.HotelSOAP.comparator.clients.a1.AgencyService a1;

  @Autowired
  @Qualifier("a2Client")
  private com.example.HotelSOAP.comparator.clients.a2.AgencyService a2;

  @GetMapping("/")
  public String home() {
    return "index";
  }

  @GetMapping("/search")
  public String searchOffers(
          @RequestParam(required = false) String city,
          @RequestParam(required = false) String startDate,
          @RequestParam(required = false) String endDate,
          @RequestParam(required = false) Double minPrice,
          @RequestParam(required = false) Double maxPrice,
          @RequestParam(required = false) Integer stars,
          @RequestParam(required = false, defaultValue = "1") int persons,
          Model model) {

    if (city != null && startDate != null && endDate != null) {

      try {
        List<Object> allOffers = new ArrayList<>();

        // 💡 adapt to YOUR actual SOAP method name
        List<?> o1 = a1.searchAvailability(
                city, startDate, endDate,
                minPrice, maxPrice, stars, persons);
        List<?> o2 = a2.searchAvailability(
                city, startDate, endDate,
                minPrice, maxPrice, stars, persons);

        allOffers.addAll(o1);
        allOffers.addAll(o2);

        model.addAttribute("offers", allOffers);
        model.addAttribute("hasResults", true);

        if (allOffers.isEmpty()) {
          model.addAttribute("message", "Aucune offre trouvée auprès des agences.");
        }
      }
      catch (Exception e) {
        model.addAttribute("error", "Erreur: " + e.getMessage());
      }
    }

    // put form data back into model
    model.addAttribute("city", city);
    model.addAttribute("startDate", startDate);
    model.addAttribute("endDate", endDate);
    model.addAttribute("minPrice", minPrice);
    model.addAttribute("maxPrice", maxPrice);
    model.addAttribute("stars", stars);
    model.addAttribute("persons", persons);

    return "search";
  }

  @GetMapping("/reserve")
  public String reserveForm(
          @RequestParam String offerId,
          @RequestParam String agency, // A1 or A2
          Model model) {

    model.addAttribute("offerId", offerId);
    model.addAttribute("agency", agency);
    return "reserve";
  }

  @PostMapping("/reserve")
  public String processReservation(
          @RequestParam String offerId,
          @RequestParam String agency, // A1 or A2
          @RequestParam String clientName,
          @RequestParam String clientEmail,
          @RequestParam String clientPhone,
          Model model) {

    try {
      String confirmationCode;

      if (agency.equals("A1")) {
        confirmationCode = a1.makeReservation(
                offerId, clientName, clientEmail, clientPhone
        );
      } else {
        confirmationCode = a2.makeReservation(
                offerId, clientName, clientEmail, clientPhone
        );
      }

      if (confirmationCode != null && !confirmationCode.startsWith("ERROR")) {
        model.addAttribute("success", true);
        model.addAttribute("confirmationCode", confirmationCode);
        model.addAttribute("clientName", clientName);
        model.addAttribute("clientEmail", clientEmail);
      } else {
        model.addAttribute("error", "Booking failed: " + confirmationCode);
      }

    } catch (Exception e) {
      model.addAttribute("error", "Error: " + e.getMessage());
    }

    return "confirmation";
  }

}

