
package com.example.HotelSOAP.comparator.clients.a1;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AgencyService", targetNamespace = "http://service.agency.HotelTP.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AgencyService {


    /**
     * 
     * @param persons
     * @param city
     * @param endDate
     * @param minPrice
     * @param maxPrice
     * @param stars
     * @param startDate
     * @return
     *     returns java.util.List<com.example.HotelSOAP.comparator.clients.a1.AvailabilityOffer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchAvailability", targetNamespace = "http://service.agency.HotelTP.example.com/", className = "com.example.HotelSOAP.comparator.clients.a1.SearchAvailability")
    @ResponseWrapper(localName = "searchAvailabilityResponse", targetNamespace = "http://service.agency.HotelTP.example.com/", className = "com.example.HotelSOAP.comparator.clients.a1.SearchAvailabilityResponse")
    @Action(input = "http://service.agency.HotelTP.example.com/AgencyService/searchAvailabilityRequest", output = "http://service.agency.HotelTP.example.com/AgencyService/searchAvailabilityResponse")
    public List<AvailabilityOffer> searchAvailability(
        @WebParam(name = "city", targetNamespace = "")
        String city,
        @WebParam(name = "startDate", targetNamespace = "")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        String endDate,
        @WebParam(name = "minPrice", targetNamespace = "")
        Double minPrice,
        @WebParam(name = "maxPrice", targetNamespace = "")
        Double maxPrice,
        @WebParam(name = "stars", targetNamespace = "")
        Integer stars,
        @WebParam(name = "persons", targetNamespace = "")
        int persons);

    /**
     * 
     * @param clientName
     * @param clientEmail
     * @param offerId
     * @param clientPhone
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeReservation", targetNamespace = "http://service.agency.HotelTP.example.com/", className = "com.example.HotelSOAP.comparator.clients.a1.MakeReservation")
    @ResponseWrapper(localName = "makeReservationResponse", targetNamespace = "http://service.agency.HotelTP.example.com/", className = "com.example.HotelSOAP.comparator.clients.a1.MakeReservationResponse")
    @Action(input = "http://service.agency.HotelTP.example.com/AgencyService/makeReservationRequest", output = "http://service.agency.HotelTP.example.com/AgencyService/makeReservationResponse")
    public String makeReservation(
        @WebParam(name = "offerId", targetNamespace = "")
        String offerId,
        @WebParam(name = "clientName", targetNamespace = "")
        String clientName,
        @WebParam(name = "clientEmail", targetNamespace = "")
        String clientEmail,
        @WebParam(name = "clientPhone", targetNamespace = "")
        String clientPhone);

}
