
package com.example.HotelTP.agency.clients.h2;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelService", targetNamespace = "http://hotel.example.com/soap")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelService {


    /**
     * 
     * @param persons
     * @param start
     * @param end
     * @param token
     * @return
     *     returns java.util.List<com.example.HotelTP.agency.clients.h2.AvailabilityOffer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkAvailability", targetNamespace = "http://hotel.example.com/soap", className = "com.example.HotelTP.agency.clients.h2.CheckAvailability")
    @ResponseWrapper(localName = "checkAvailabilityResponse", targetNamespace = "http://hotel.example.com/soap", className = "com.example.HotelTP.agency.clients.h2.CheckAvailabilityResponse")
    @Action(input = "http://hotel.example.com/soap/HotelService/checkAvailabilityRequest", output = "http://hotel.example.com/soap/HotelService/checkAvailabilityResponse")
    public List<AvailabilityOffer> checkAvailability(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "start", targetNamespace = "")
        String start,
        @WebParam(name = "end", targetNamespace = "")
        String end,
        @WebParam(name = "persons", targetNamespace = "")
        int persons);

    /**
     * 
     * @param mainGuest
     * @param offerId
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "book", targetNamespace = "http://hotel.example.com/soap", className = "com.example.HotelTP.agency.clients.h2.Book")
    @ResponseWrapper(localName = "bookResponse", targetNamespace = "http://hotel.example.com/soap", className = "com.example.HotelTP.agency.clients.h2.BookResponse")
    @Action(input = "http://hotel.example.com/soap/HotelService/bookRequest", output = "http://hotel.example.com/soap/HotelService/bookResponse")
    public String book(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "offerId", targetNamespace = "")
        String offerId,
        @WebParam(name = "mainGuest", targetNamespace = "")
        Client mainGuest);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://hotel.example.com/soap", className = "com.example.HotelTP.agency.clients.h2.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://hotel.example.com/soap", className = "com.example.HotelTP.agency.clients.h2.LoginResponse")
    @Action(input = "http://hotel.example.com/soap/HotelService/loginRequest", output = "http://hotel.example.com/soap/HotelService/loginResponse")
    public String login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
